### ISSUE TITLE
Document default filetypes

### ISSUE THREAD

**Issue by andrewferrier** [gaoDean/autolist.nvim#1]
autolist.nvim is great! However, both the README and the help are a bit vague on what a 'list marker' is or what syntax is supported. Having read through some of the code, I now know it's targeted at Markdown files primarily. However, there are other markup formats, like AsciiDoc, LaTeX, etc. which could all be potentially supported by `autolist.nvim`. I don't know if you have any plans to support them, but highlighting what's supported today might make it easier for folks to adopt your plugin. Just a thought.

Thanks for working hard to create this!

**Comment by gaoDean** [comment]
Hi, I'm currently debating on whether to support **all** lists, like latex HTML, but that increases the complexity of the plugin, which is made to be minimal. The other option is to make a new repository, but it would be a hassle to keep both up to date. What do you think?

**Comment by andrewferrier** [comment]
Well, FWIW, I would definitely not split these out into separate plugins. There are plugins a lot more complex than this one! You might have to do some modularization, but I think improving the "quality of living" for lists generally is worthy of a single plugin. I think you'll find there's more commonality than difference between those filetypes.

Just to be clear though, that wasn't my original motivation for the issue; that was simply a suggestion to clarify the documentation so that folks understand what it does *today* :) It's not even 100% clear what you mean by "list" - do you mean the quickfix list, for example? I would just suggest a few examples and some clarification over what filetype(s) are supported today...

**Comment by gaoDean** [comment]
Thanks for that, I will now commit to one plugin, and to answer the main issue, I will put in a filler video, and create a better one when I have the time.
