### ISSUE TITLE
enter in between sentence deletes the last part

### ISSUE THREAD

**Issue by gaoDean** [gaoDean/autolist.nvim#10]
```
- test1 test2 | test3 test4
cursor here --^
```
when enter is pressed
```
- test1 test2
- |
```

**Comment by andrewferrier** [comment]
I've noticed this too. It's annoying if you are trying to convert one list item into two. In my case, vim undo/git can restore the content, but if those were disabled, this would be a bigger problem.

**Comment by gaoDean** [comment]
yeah easy fix, but as I said, this is going through a rewrite, so not much use in fixing. Just a few more days!

**Comment by gaoDean** [comment]
alright, this is fixed in the rewrite, tell me what you think @andrewferrier
