### ISSUE TITLE
New line above first element in a numbered list

### ISSUE THREAD

**Issue by oncomouse** [gaoDean/autolist.nvim#11]
I'm finding this plugin really useful, but I've hit on a bit of a snag with numbered lists. In addition to the mapping for `o` to add a new line below a list item and re-number everything, I wanted to be able to hit `O` to add the same above. I added `vim.cmd("nmap <buffer> O O<cmd>lua require('autolist').list()<cr>")` to my `ftplugin/markdown.lua` file, which works except if I press `O` on the first item of a numbered list.

So, if I have a file like this and my cursor is represented by `|`:

~~~ markdown
1. |First
2. Second
3. Third
~~~

When I press `O`, I want the following to happen:

~~~ markdown
1. |
2. First
3. Second
4. Third
~~~

But currently, this is what results:

~~~ markdown
|
1. First
2. Second
3. Third
~~~

Would it be possible/desirable to add this behavior?

**Comment by gaoDean** [comment]
yeah that would be fine to add, would be much easier after the rewrite, I just need to iron out a few bugs.

**Comment by gaoDean** [comment]
@oncomouse done, tell me what you think. keep in mind there's been a rewrite, so any configuration options will be overrided, although that shouldn't be a problem for this.
