### ISSUE TITLE
Mardown: list "inversion" on top level list items creates indentation.

### ISSUE THREAD

**Issue by louis-vinchon** [gaoDean/autolist.nvim#15]
With the default configuration loaded, and this example buffer:

```markdown
- item
```

Running the `<C-r>` keymap in insert mode on this item will yield the following (notice the indentation before the `1.` item marker):

```markdown
  1. item
```

The behavior was not observed on child list items.

**Comment by gaoDean** [comment]
that is actually a desired behavior, I just forgot to include it in the docs. I agree that this should be a configurable behavior, not a default one.

**Comment by gaoDean** [comment]
fixed, also updated the docs
