### ISSUE TITLE
Markdown: when NOT in a list, checkbox "inversion" throws errors.

### ISSUE THREAD

**Issue by louis-vinchon** [gaoDean/autolist.nvim#16]
With the default configuration and the following example buffer:

```markdown
[ ] test
```

Running the `<C-r>` keymap on the checkox line throws the following error:

```
E5108: Error executing lua ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:142:
 attempt to perform arithmetic on local 'list_start_num' (a nil value)
stack traceback:
        ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:142: in function 'recal
'
        ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:36: in function 'check_
recal'
        ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:228: in function 'inver
t'
        [string ":lua"]:1: in main chunk
```
Note that the checkbox is checked anyway.

While chekcboxes are supposed to be in lists, it'd be nicer not to get a complete stacktrace if they are not, a single line warning about the required list context would be preferable.

**Comment by gaoDean** [comment]
would you want a list of checkboxes that have checkboxes not preceded by list markers?

**Comment by gaoDean** [comment]
> would you want a list of checkboxes that have checkboxes not preceded by list markers?

for example:
```
[ ] test
[ ] test
[ ] test
```
or does that not follow convention

**Comment by louis-vinchon** [comment]
> would you want a list of checkboxes that have checkboxes not preceded by list markers?

No, because it is apparently not the correct syntax for checkboxes. What I really want is the error message not to be a stack trace that takes half my screen every time I mistakenly, or accidentaly, try to "invert" such "checkbox".

What I think would be much nicer is a simple "try catch" and in your catch block, something like:

```lua
vim.notify("autolist.nvim cannot invert a checkbox because of incorrect syntax: checkboxes have to be in a list.", vim.log.levels.WARN)
```
Which should, by default, display the message in your command line:
- No screen bloat, much cleaner.
- The user has a clear explanation of what the issue is and how to fix it.

**Comment by louis-vinchon** [comment]
If you feel inspired you could have a prompt asking the user if they want autolist to automatically fix the checkbox. Just and idea.

**Comment by gaoDean** [comment]
Well the syntax error is fixed, at least, I'll think about the prompt.

**Comment by gaoDean** [comment]
I just realised that inverting the checkbox does work for checkboxes without list entries. Should I remove that, or just leave it in?

**Comment by louis-vinchon** [comment]
[] no list entry + no space between brackets
[ ] no list entry + space between brackets
- [] list entry + no space between brackets
- [ ] list entry + space between brackets

I would stick with what works and display a warning of all other cases.
