### ISSUE TITLE
Mardown: in a child list, "inversion" does not work / partially works.

### ISSUE THREAD

**Issue by louis-vinchon** [gaoDean/autolist.nvim#17]
With the default configuration and the following buffer:

```markdown
1. Top level
  - 1
  - 2
  - 3
2. Top level
  1. a
  2. b
  3. c
```

Inverting an item of the unordered child list with the `<C-r>` keymap only inverts the line the cursor is on.
Inverting an item of the ordered child list with the `<C-r>` keymap does not invert anything and the cursor moves one character to the left.

**Comment by gaoDean** [comment]
alright, for some reason ive tried everything but cant get the cursor to move to the end of the line, but now inverting can invert the entire list. Try it out!
