### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by louis-vinchon** [gaoDean/autolist.nvim#18]
I would love to see more documentation on the `recal_hooks` option; one feature I would like is if the ordered lists were re-ordered when a line is deleted with `dd` in normal mode for example, which is no happening by default.

**Comment by gaoDean** [comment]
you can remap them by your self, I can add a feature to do that but you would still need to input the hook that you want.

**Comment by gaoDean** [comment]
Okay, added config option for custom mappings. Will add to documentation later, look for a new release later this week.
