### ISSUE TITLE
Indenting on <Tab>

### ISSUE THREAD

**Issue by ignamartinoli** [gaoDean/autolist.nvim#19]
It would be nice if, after pressing `<CR>` and getting the list item written, pressing `<Tab>` just after that could indent the item.

This is an example:

```
Before     Input     After
----------------------------
- Item               - Item
- |        <Tab>         - |
```

**Comment by gaoDean** [comment]
alright, this should be implemented, the docs will come.

**Comment by ignamartinoli** [comment]
thanks! also doing the opposite with `<S-Tab>` would be awesome

**Comment by gaoDean** [comment]
yeah, its already implemented.

**Comment by ignamartinoli** [comment]
I just tried it and it works a little bit weird.

With this text and the cursor (the `|` character) on the second item

```markdown
- Some item
- |
```

after pressing `<Tab>` the result is

```markdown
- Some item
       |
```

with the item disappearing altogether and with 7 spaces indentation.

The expected behaviour should be (supposing that the user has `shiftwidth=4`)

```markdown
- Some item
    - |
```

**Comment by gaoDean** [comment]
Ohh my bad, I didn’t take into account spaces instead of tabs (I’m an adamant tabs user). I’ll fix this tomorrow when I get the time.

**Comment by ignamartinoli** [comment]
Ahahaha, no problem, I adamantly use tabs too in structured programming languages, but in things like Haskell, Erlang, LaTeX and Markdown I use spaces since the code tends to focus on beauty more than structure

**Comment by ignamartinoli** [comment]
Actually, I realized that a lot of users (me included) set the indentation in `after/ftplugin`, so on load I don't think the plugin could know the indentation each user uses. One workaround could be add a `setup` field for indentation style

**Comment by gaoDean** [comment]
What do you mean by `setup` field? My current idea is just to take it from `expandtab` and `tabstop`

**Comment by ignamartinoli** [comment]
That could be possible, but I'm not sure if the plugin would be able to get the user indentation level if it's set in `after/ftplugin`.

If that wasn't possible, then a solution could be add a parameter to the plugin with something like

```lua
use {
  'gaoDean/autolist.nvim',
  config = function () require 'autolist'.setup {
    style = 'spaces', 
    depth = 2
  } end
}
```

**Comment by ignamartinoli** [comment]
Try first if it's possible to fetch the options defined by the user in `after/ftplugin`, if that's not possible then you can use that alternative.

Most users set the indentation on that directory because, since it gets executed after plugin initialization, it won't be modified

**Comment by gaoDean** [comment]
Sorry I haven’t fixed this, I’m currently busy working on another project right now. I’ll get back to you in a week or so.

**Comment by ignamartinoli** [comment]
@gaoDean no problem, there's no rush :wink:

**Comment by gaoDean** [comment]
@ignamartinoli alright, hopefully it works this time...

**Comment by schoblaska** [comment]
Hmm, I think this broke something for me:

```
E5108: Error executing lua ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:136: attempt to index field 'cmd' (a function value)
stack traceback:
        ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:136: in function 'indent'
        [string ":lua"]:1: in main chunk
```

**Comment by ignamartinoli** [comment]
It's working _almost_ perfectly.

After using `<Tab>`, is added one space **before** the cursor and one **after** the cursor, like this:

```
-·Some·item¶
····-··|·¶
```

This should be the result:

```
-·Some·item¶
····-·|¶
```

It's **almost** done :D

`space`: `·`
`eol`: `¶`

**Comment by gaoDean** [comment]
Does this happen with `<c-t>`? Also, how did you fix the error from before? I'll test with `expandtab` once i get home, but how is tabbed working for you?

**Comment by gaoDean** [comment]
@ignamartinoli Ok don't worry about answering the above questions, but it should work now for expandtab, at least for me.

**Comment by gaoDean** [comment]
@joeyschoblaska Perhaps try the newest version, see if that fixes things. If not, post the conditions/environment that made the issue happen here, also the version of neovim, Thanks.

**Comment by schoblaska** [comment]
I'm using Neovim 0.7.2:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```

I think the issue is that you're indexing `vim.cmd`, which was only officially released a few days ago in Neovim 0.8: https://github.com/neovim/neovim/pull/19238

I'm planning on upgrading to 0.8 soon anyway, but just FYI this plugin will not work in v0.7.2 or below.

Edit: I upgraded to 0.8 and now the fix works. Thanks!

**Comment by ignamartinoli** [comment]
@gaoDean you're gonna hate me hehe.

The space **before** the cursor is fixed, now there's only a trailing space inserted **after** the cursor that shouldn't be there:

```
-·Some·item¶
····-·|·¶
       ^
```

**Comment by gaoDean** [comment]
@joeyschoblaska Ohh, thanks for telling me. I should put that in the readme, but I'll test out feedkeys later, do you know if thats more supported in older versions?

**Comment by schoblaska** [comment]
I believe you can just use the original `vim.cmd` syntax:

```lua
vim.cmd.normal{"i" .. ctrl_t .. " ", bang = true}
-- becomes:
vim.cmd("normal! i" .. ctrl_t .. " ")
```

**Comment by gaoDean** [comment]
@joeyschoblaska @ignamartinoli okok all should be fixed, used `nvim_feedkeys` so lower versions of nvim should be supported, and the trailing space should be abolished...

**Comment by schoblaska** [comment]
Works great! Thanks for fixing this, and thanks for the great plugin :)

**Comment by ignamartinoli** [comment]
@gaoDean thanks! It works perfectly now
Congrats for the new feature and thanks for the awesome plugin :D
