### ISSUE TITLE
Duplicate bullet on <CR>

### ISSUE THREAD

**Issue by linduxed** [gaoDean/autolist.nvim#20]
I've noticed that unordered lists seem to be adding an extra list marker at the start of the line.

## Examples
Having the following markdown...:
```markdown
- Foo
- Bar|
```
...where the `|` is the cursor, pressing `<CR>` results in this:
```markdown
- Foo
- Bar
- - |
```
Same happens with checklists:
```markdown
- [ ] Foo
- [ ] Bar
- [ ] - |
```
This does *not* seem to be happening with numbered lists.

## Commit history
I ran a `git bisect`, and the first commit where this behaviour seems to be happening is in 2012ec9c9adc0e54b1e5f66ae44fbf652d198581. I have, at the moment, not investigated what changes in the patch could be causing this change in behaviour.

**Comment by linduxed** [comment]
The disabling of almost all plugins and mappings seems to have fixed the issue. Will investigate further.

**Comment by linduxed** [comment]
It seems like both of these plugins, when enabled (no custom configuration), results in the behavior above:

- https://github.com/preservim/vim-markdown
- https://github.com/sheerun/vim-polyglot

I have yet to figure out whether there's some configuration option that can prevent this behavior.

I guess this issue can be closed, since the bug in question is caused by the interaction of two plugins.

EDIT: For anyone in the future, wondering if I solved this somehow through configuration, I did not. I removed the `vim-markdown` plugin and configured `vim-polyglot` to not load any of its `markdown` code.

**Comment by gaoDean** [comment]
Alright, I'll put this in troubleshooting in the wiki.

**Comment by gaoDean** [comment]
@linduxed 
I think you can just disable the auto bullet in vim-markdown: 
https://github.com/preservim/vim-markdown#do-not-automatically-insert-bulletpoints

**Comment by linduxed** [comment]
Yes, indeed, disabling this configuration option does solve the issue! Thanks for pointing this out!
