### ISSUE TITLE
Code suggestion

### ISSUE THREAD

**Issue by louis-vinchon** [gaoDean/autolist.nvim#22]
Reference: https://github.com/gaoDean/autolist.nvim/blob/main/lua/autolist/init.lua#L8-L15

`:he vim.tbl_extend()` might help you. There's also `vim.tbl_filter()` in case you only need a set of methods / properties.

**Comment by gaoDean** [comment]
Sorry, I don't know what you mean. Could you explain further?

**Comment by louis-vinchon** [comment]
By the looks of it, you are trying to merge the entire `auto` table into the `M` table.

That could be done with `vim.tbl_extend("keep", M, auto)`.

**Comment by gaoDean** [comment]
oh, that makes sense. I thought you were talking about the config, sorry.

**Comment by gaoDean** [comment]
hmm, table_extend doesn't seem to work on function pointers

**Comment by gaoDean** [comment]
whoops I didn't set M to the return value, it works now, thanks!
edit: doesn't

**Comment by gaoDean** [comment]
actually it doesn't work, just gives
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'new' (a nil value)
```

**Comment by louis-vinchon** [comment]
Unfortunate, I might contribute later and see if I can make it work.

**Comment by gaoDean** [comment]
Alright thx

**Comment by gaoDean** [comment]
alright this commit should implement the desired refactor
