### ISSUE TITLE
bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by mojasp** [gaoDean/autolist.nvim#24]
When editing filetypes that are *not* markdown or txt, i am getting the following error:

` 
E5108: Error executing lua ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:70: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...te/pack/packer/start/autolist.nvim/lua/autolist/auto.lua:70: in function 'new'
        [string ":lua"]:1: in main chunk
`

I had a brief look at the code but don't understand why the erorr happens, the filetype table should never be nil... Strangely the plugin still works when editing markdown or txt files. The plugin was working for me before updating my plugins, i cannot say exactely what is causing this error.

**Comment by gaoDean** [comment]
ok should be fixed, just me forgetting something while refactoring

**Comment by mojasp** [comment]
That was fast! Thanks, very cool plugin by the way!

**Comment by gaoDean** [comment]
Thanks!
