### ISSUE TITLE
Conflicts with code blocks that include certain comments.

### ISSUE THREAD

**Issue by AndOrangutan** [gaoDean/autolist.nvim#26]
Greetings,

I have been recently learning quite a bit of SQL recently and have found that in code blocks the `--` inline comments make this plugin think I want a list. Maybe there is some way to avoid fenced code blocks?

Expected (after pressing 'o' I am inserted on a blank line):
```markdown
blah blah blah look at this code:

\```sql
-- Example Comment
|
\```
```

Current behavior:
```markdown
blah blah blah look at this code:

\```sql
-- Example Comment
-|
\```
```
Really loving this plugin, it is so much smoother in operation than bullets :)

**Comment by gaoDean** [comment]
alright, sorry for the wait but this should be fixed now?
