### ISSUE TITLE
Feat Request : Auto list for programming languages 

### ISSUE THREAD

**Issue by LamprosPitsillos** [gaoDean/autolist.nvim#27]
[Draft]

It's a bit annoying trying to write out a map or a list in programming languages and this plug-in looks capable of helping. 
I am not sure this can be done with snipets (as it can go on infinitely) but still felt it was worth a conversation over.

Ex.
```c
int nums[]={|};
int nums[]={1,|};
int nums[]={1,2,|};
// It adds a comma and moves the cursor ready to insert another item
```

```python
map = {|} 
map = {1:|}
map = {1:"hello",|}
# It adds : and , as necessary to make inserting elements super easy and fast
nums = [|]
nums = [1,|]
```
Treesitter can be used to only activate this functionality when in the appropriate nodes (@lists or something..).

**Comment by gaoDean** [comment]
Hmm, I’m a bit busy atm, might come back to this one.
