### ISSUE TITLE
Does't work properly with filetype=org after nvim 0.8 update

### ISSUE THREAD

**Issue by hisbaan** [gaoDean/autolist.nvim#28]
Autolist.nvim doesn't seem to work when the filetype is org. I have included org in the enabled filetypes in the config (see below)

Here is a screencast showing the issue:

[![asciicast](https://asciinema.org/a/dTy1zGcoIERMPGsEBVxRg311j.svg)](https://asciinema.org/a/dTy1zGcoIERMPGsEBVxRg311j)

I have yet to write a minimal config to test it with, but I figured that it was still worth opening an issue. I'll update this when I get the time to do that.

Here is my config:
```
require('autolist').setup({
	enabled = true,
	list_cap = 50,
	colon = {
		indent_raw = false,
		indent = true,
		preferred = "-"
	},
	invert = {
		indent = false,
		toggles_checkbox = true,
		ul_marker = "-",
		ol_incrementable = "1",
		ol_delim = ".",
	},
	lists = {
		preloaded = {
			generic = {
                -- "unordered",
				"[-+]",
				"digit",
				"ascii",
			},
			latex = {
				"latex_item",
			},
		},
		filetypes = {
			generic = {
				"markdown",
                "org",
				"text",
			},
			latex = {},
		},
	},
	recal_function_hooks = {
		"invert",
		"new",
	},
	checkbox = {
		left = "%[",
		right = "%] ",
		fill = "X",
	},
	insert_mappings = {
		invert = { "<c-r>+[catch]" },
		new = { "<CR>" },
		tab = { },
		detab = { },
		recal = { },
		indent = {
            "",
            "",
		},
	},
	normal_mappings = {
		new = {
			"o",
			"O+(true)",
		},
		tab = { },
		detab = { },
		recal = { "dd" },
	},
})
```

Edit: After further research, this seems to be a conflict between `autolist.nvim` and `nvim-orgmode`. Without `nvim-orgmode`, however, pressing `<CR>` in insert mode does nothing until the filetype is reloaded (`:set ft=org` or `:e`). The normal mode mappings like `o` still work, so I think that it is related to the way insert mode mappings are done within `autolist.nvim` (using autocmds instead of just a normal mapping)

**Comment by gaoDean** [comment]
This does seem to be a plug-in conflict, but the auto commands in the plug-in are just file type commands that map keys. Mainly it does this to set the mappings on correct file types.

**Comment by gaoDean** [comment]
Another thing, (I am very unfamiliar with org), are you sure it isn’t nvim-orgmode that does the file type checking? It might be that without the orgmode plugin vim doesn’t know what file type it is. Try checking the file type of org files without nvim-orgmode, though it is weird that other commands work.

**Comment by gaoDean** [comment]
> I think that it is related to the way insert mode mappings are done within autolist.nvim 

The insert mode mappings are done with `inoremap`, and the normals are `nnoremap`, with everything else the same, so I can’t see why there would be a difference.

**Comment by hisbaan** [comment]
> nvim-orgmode that does the file type checking

I checked without `nvim-orgmode` and the filetype org still works, so that isn't it.

I created a minimal config (see below) and that allowed `autolist.nvim` to do it's job, so it must be something else in my configuration. If possible, I'd like for this to remain (you can close it, so long as I can still comment after that), so I can post my solution if I end up finding one for others searching. Thanks for the quick responses, and thanks for making a plugin that's so useful I'm procrastinating assignments to try and get it working :sweat_smile: 

# Minimal Config

run with `nvim --noplugin -u minimal.lua temp.org`

```lua 
vim.cmd [[packadd packer.nvim]]

local packer = require('packer')
packer.init {
    enable = true,
    threshold = 0,
}

local use = packer.use
packer.reset()

packer.startup({function()
    use { 'gaoDean/autolist.nvim' }
end})

require('autolist').setup({
	enabled = true,
	list_cap = 50,
	colon = {
		indent_raw = false,
		indent = true,
		preferred = "-"
	},
	invert = {
		indent = false,
		toggles_checkbox = true,
		ul_marker = "-",
		ol_incrementable = "1",
		ol_delim = ".",
	},
	lists = {
		preloaded = {
			generic = {
                -- "unordered",
				"[-+]",
				"digit",
				"ascii",
			},
			latex = {
				"latex_item",
			},
		},
		filetypes = {
			generic = {
				"markdown",
                "org",
				"text",
			},
			latex = {},
		},
	},
	recal_function_hooks = {
		"invert",
		"new",
	},
	checkbox = {
		left = "%[",
		right = "%] ",
		fill = "X",
	},
	insert_mappings = {
		invert = { "<c-r>+[catch]" },
		new = { "<CR>" },
		tab = { },
		detab = { },
		recal = { },
	},
	normal_mappings = {
		new = {
			"o",
			"O+(true)",
		},
		tab = { },
		detab = { },
		recal = { "dd" },
	},
})
```

**Comment by hisbaan** [comment]
I narrowed it down to  `nvim-orgmode/orgmode/lua/orgmode/config/mappings.init.lua:104` which at the time of writing this is:
```lua
org_return = m.action('org_mappings.org_return', { modes = { 'i' }, opts = { desc = 'org return' } }),
```
I'm not sure exactly what function `org_return` is supposed to do (it's not documented), but disabling this mapping fixes things. It's not a new change either (3 months ago), so something in 0.8 must have caused these two mappings to 

The formal fix, for those looking at this in the future, is:
```lua
require('orgmode').setup({
    mappings = {
        org = {
            org_return = {}
        }
    }
})
```

**Comment by gaoDean** [comment]
> Thanks for the quick responses, and thanks for making a plugin that's so useful I'm procrastinating assignments to try and get it working 

Lmao

**Comment by gaoDean** [comment]
Ironic that I too was procrastinating assignments when this was first being developed lol

**Comment by gaoDean** [comment]
Also, congrats on the fix! I’ll add it to the docs later
