### ISSUE TITLE
invert.normal_mapping isn't created

### ISSUE THREAD

**Issue by mawkler** [gaoDean/autolist.nvim#31]
`invert.normal_mapping` doesn't seem to create a keymap. With the config:

```lua
use { 'gaoDean/autolist.nvim',
  ft = { 'markdown', 'text', 'latex' },
  config = function()
    require('autolist').setup({
      invert = {
        normal_mapping = '<space>x',
      },
    })
  end,
}
```

`:map <space>x` outputs "No mapping found".

Here's a full config to reproduce:

<details>
<summary><b>Click to expand</b></summary>

```lua
-- Ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(vim.fn.expand('~/.local/share/nvim/site'))

-- Append test directory
local test_dir = vim.fn.expand('~/code-other/nvim-test-config')
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- Install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd('packadd packer.nvim')
  install_plugins = true
end

local packer = require('packer')

packer.init({
  package_root = test_dir .. '/pack',
  compile_path = test_dir .. '/plugin/packer_compiled.lua'
})

packer.startup(function()
  function Use(module)
    use(require(string.format('configs.%s', module)))
  end

  -- Packer can manage itself
  packer.use 'wbthomason/packer.nvim'

  use { 'gaoDean/autolist.nvim',
    ft = { 'markdown', 'text', 'latex' },
    config = function()
      require('autolist').setup({
        invert = {
          normal_mapping = '<space>x',
        },
      })
    end,
  }

  if install_plugins then
    packer.sync()
  else
    -- load plugins at your earliest convenience
    vim.defer_fn(function()
      vim.cmd('doautocmd User LoadPlugins')
    end, 1)
  end
end)
```

</details>

**Comment by gaoDean** [comment]
Close, but I think your config isn’t correct. This is what it should be: 
```lua 
normal_mappings = {
    new = {
        "o",
        "O+(true)",
    },
    tab = { ">>" },
    detab = { "<<" },
    recal  = { "dd" },
},
```

**Comment by mawkler** [comment]
@gaoDean What I would like is to use `<leader>x` to toggle checkboxes. I took the config from the README [here](https://github.com/gaoDean/autolist.nvim/blob/88c99f131f63775bf100ab6ec7078701ae0f34c8/README.md?plain=1#L86) and I guessed by the name that it would create a mapping for me?

I'm not quite sure how I can use the config from your previous comment in order to create the mapping?

**Comment by gaoDean** [comment]
@melkster 
```lua
normal_mappings = {
    invert = { "<leader>x" },
},
```

**Comment by gaoDean** [comment]
> @gaoDean What I would like is to use `<leader>x` to toggle checkboxes. I took the config from the README [here](https://github.com/gaoDean/autolist.nvim/blob/88c99f131f63775bf100ab6ec7078701ae0f34c8/README.md?plain=1#L86) and I guessed by the name that it would create a mapping for me?
> 
> I'm not quite sure how I can use the config from your previous comment in order to create the mapping?

For most things, the wiki is better.

**Comment by gaoDean** [comment]
good to close?

**Comment by mawkler** [comment]
@gaoDean Thank you, I forgot to look for a GitHub wiki.

However, `normal_mappings.invert` doesn't quite work as expected either. Adding the following to my config:

```lua
normal_mappings = {
  invert = { '<leader>x' },
}
```

, maps `<leader>x` to:

```lua
*@<Space>x<Cmd>lua require('autolist').invert()
```

which means that it executes the mapping twice, first it literally presses `<space>x` and then it calles `autolist.invert()`.

This works however:

```lua
vim.keymap.set('n', '<leader>x', require('autolist').invert)
```

**Comment by gaoDean** [comment]
oh I didn’t think about that, then you would want to add the extra catch option like this: `<leader>x+[catch]` so it “catches” the mapping. This is also said in the wiki.

**Comment by gaoDean** [comment]
alr, imma close this now if there are no further issues.

**Comment by mawkler** [comment]
Ok, yeah `<leader>x+[catch]` works. Thanks!
