### ISSUE TITLE
Include whitespace after checkbox

### ISSUE THREAD

**Issue by mawkler** [gaoDean/autolist.nvim#32]
The current behaviour after pressing `<CR>` on a checkbox line is the following (where `|` is the cursor position):

```txt
- [ ] first line
- [ ]|
```

I would like for it to also create a newline after the checkbox, like this:

```txt
- [ ] first line
- [ ] |
```
I tried this:
```lua
require('autolist').setup({
  checkbox = {
    right = '%] ',
  },
})
```

But that makes no difference.

**Comment by gaoDean** [comment]
Huh that’s weird, I’ll give it a look in a bit

**Comment by mawkler** [comment]
Oups

**Comment by gaoDean** [comment]
should be fixed, try it out.

**Comment by mawkler** [comment]
Works, now thank you very much!
