### ISSUE TITLE
feature: force recalculate when appropriate

### ISSUE THREAD

**Issue by mawkler** [gaoDean/autolist.nvim#33]
I think dot-repeat support for `autolist.invert()` would be awesome. The primary use case I have in mind is for toggling multiple check boxes after one another.

**Comment by gaoDean** [comment]
Just so I don’t accidentally close the tab and lose it: https://www.vikasraj.dev/blog/vim-dot-repeat

**Comment by gaoDean** [comment]
done with #35, sorry it took a long time, i was just doing other things

**Comment by mawkler** [comment]
@gaoDean Thank you very much. However, it doesn't seem to work for me. Is it supposed to create a mapping, because `:map .` says that I don't have one?

I tried with this config:

```lua
use { 'gaoDean/autolist.nvim',
  config = function ()
    require('autolist').setup({})
  end
}
```

And on this Markdown file:

```
- [ ] foo
- [ ] bar
```

**Comment by gaoDean** [comment]
@mawkler Yeah there’s no default invert mapping.
```lua
use { 'gaoDean/autolist.nvim',
  config = function ()
    require('autolist').setup({
        normal_mappings = {
            invert = '<leader>i ', (your mapping here)
        },
    })
  end
}
```

i typed this on phone so there’s probs some syntax errors but check the wiki for more in depth configuration

**Comment by mawkler** [comment]
@gaoDean When testing I call `require('autolist').invert()` which works, however, pressing `.` afterwards does not repeat the invert for me when I use the config from my previous comment.

What I meant is that there doesn't seem to be a mapping for `.`, but perhaps that's not how the dot repeat is implemented 🙂

**Comment by gaoDean** [comment]
So if u look at the article posted above, dot repeat is implemented through operatorfunc and g@, and if u look at the commit, that’s exactly what it does. Try doing :lua vim.o.operatorfunc = v:lua.require’autolist’.invert and pressing g@

**Comment by mawkler** [comment]
@gaoDean Yes, if I do `:lua vim.o.operatorfunc = "v:lua.require'autolist'.invert"` and press `g@l` (it seems to expect a motion after I press `g@`) the list gets inverted as expected

**Comment by gaoDean** [comment]
@gaoDean mhm, yes that is the desired output. Using the below mapping, pressing `<leader>i` and then pressing `.` will repeat.
```lua
use { 'gaoDean/autolist.nvim',
  config = function ()
    require('autolist').setup({
        normal_mappings = {
            invert = '<leader>i ', -- (your mapping here)
        },
    })
  end
}
```

**Comment by mawkler** [comment]
@gaoDean I'm not sure if this is related to the dot repeating problem, but I tried your suggested config, but after getting an error and changing it according to the helpdocs to the following, I don't get an error but it doesn't seem to create any normal mode mapping regardless of what I set the `mapping` string to:

```lua
use { 'gaoDean/autolist.nvim',
  config = function ()
    require('autolist').setup({
      invert = {
        mapping = '<leader>x',
      }
    })
  end
}
```

What I've done is this:

```lua
use { 'gaoDean/autolist.nvim',
  config = function ()
    require('autolist').setup({})

    vim.keymap.set('n', '<leader>x', require('autolist').invert)
  end
}
```

but as previously mentioned, dot repeating doesn't work.

**Comment by gaoDean** [comment]
@mawkler in that case, you are not on the latest version of autolist.

**Comment by mawkler** [comment]
@gaoDean I'm on the latest commit f600383. I'm on Nvim v0.8.1 stable 🤔

**Comment by gaoDean** [comment]
@mawkler yeah u should use the wiki instead of help docs, those are outdated.

**Comment by gaoDean** [comment]
actually that is a good idea, I might remove the mappings in the config and let the user do the mappings.

**Comment by gaoDean** [comment]
ok check out latest version

**Comment by mawkler** [comment]
@gaoDean Now `autolist.invert_entry` seems to be repeatable with `.`. However, if I map it to `<leader>x` using `create_mapping_hook` like the README describes, and put the cursor anywhere that's not at the end of the line it will also delete the character after the cursor.

Also, perhaps instead of hard coding in operations like `dd`, `<<` and `>>` like the README now suggets

```lua
create_mapping_hook('n', 'dd', require('autolist').force_recalculate)
create_mapping_hook('n', '>>', require('autolist').indent)
create_mapping_hook('n', '<<', require('autolist').indent)
```

, perhaps it should be possible for the mapping to cover all motions? What I mean is that what if I delete a line and the two below it by doing `d2j`, the list would currently not be recalculated. Perhaps there should be a recalculation after every `d`, `<` or `>`, regardless of what motion or text object it is done over? 🙂

**Comment by gaoDean** [comment]
@mawkler hmm that does seem nice, but how would that be implemented? If let’s say we map d to recalculate + d, it would recalculate and await a second argument. If that argument is also d, the list would recalculate twice. This issue would be compounded with > and <. The ideal is to have it recalculate at the end of each key combo, but I don’t know of any way to do that. Do you have any ideas?

**Comment by mawkler** [comment]
@gaoDean Hmmm that's a good question. One solution is to use an autocommand that runs `force_recalculate()` on the `TextChanged` ~~and `TextYankPost`~~ events (perhaps also `InsertLeave`), and remove `force_recalculate()` from the mappings.

**Comment by gaoDean** [comment]
alright, I have added this to the readme recommended mappings

**Comment by mawkler** [comment]
@gaoDean What I meant is that autolist.nvim could create the autocommand. That would mean that most mappings wouldn't be needed. With `TextChanged` one can apparently use `vim.v.operator` to check what action was used to trigger the event.

```lua
local recalculate_commands = { 'd', '<', '>' }

vim.api.nvim_create_autocmd('TextChanged', {
  callback = function()
    if (vim.tbl_contains(recalculate_commands, vim.v.operator)) then
      -- recalculate...
    end
  end,
  group = 'autolist',
})
```

**Comment by gaoDean** [comment]
@mawkler I get what you mean, ill try that out tmr.

> That would mean that most mappings wouldn't be needed

Could you explain this?

**Comment by mawkler** [comment]
@gaoDean I meant that, if I'm not mistaken,  one can remove these lines from one's config that you currently suggest in the README:

```lua
autolist.create_mapping_hook("n", ">>", autolist.indent)
autolist.create_mapping_hook("n", "<<", autolist.indent)
```

As well as

```lua
create_mapping_hook('n', 'dd', require('autolist').force_recalculate)
```

Since the autocommand would recalculate the new list structure on each `<`/`>`/`d`.

**Comment by gaoDean** [comment]
Nah, indent handles the tab to ctrl-t conversion, but I’ll try the rest today
