### ISSUE TITLE
[Bug] activation on Markdown code snippets

### ISSUE THREAD

**Issue by ignamartinoli** [gaoDean/autolist.nvim#34]
When inside a code snippet (i.e. **Python**), if the user adds a newline under a line that ends with `:`, a list item is created

    Before          Input      After
    -------------------------------------------
    ```python       <Enter>    ```python
    def main():|               def main():
    ```                        - |
                               ```

The expected result would be

    Before          Input      After
    -------------------------------------------
    ```python       <Enter>    ```python
    def main():|               def main():
    ```                        |
                               ```

(The `|` character symbolizes the cursor)

I suggest maybe trying querying **TreeSitter** to get the type of block the cursor is in

**Comment by gaoDean** [comment]
hmm, using treesitter would add the treesitter dependency to the project right? I don't think that would be desirable.

**Comment by ignamartinoli** [comment]
I'm not sure about that, maybe since TreeSitter is a Neovim built-in, it wouldn't be a dependency

**Comment by gaoDean** [comment]
Yeah, but to have treesitter recognise these things, you need to install the parser, which you use nvim-treesitter to interface with.

**Comment by ignamartinoli** [comment]
You're right. I'm not really sure if there is a way to solve this reliably without TreeSitter

**Comment by gaoDean** [comment]
Do you know how to interface with treesitter? Help would be much appreciated. This could work, if this was a treesitter-specific option.

**Comment by ignamartinoli** [comment]
I actually have no idea eheh. Maybe we could ask for help to some other plugin author that has worked with `treesitter`

**Comment by mrjones2014** [comment]
I have worked a little bit with treesitter and we could make it an optional feature that only works if you've installed the Treesitter parser, but not strictly a dependency. I just ran into this myself so perhaps I'll work on a PR.

**Comment by gaoDean** [comment]
@mrjones2014 yeah that makes sense, if you have time, that would be great!
