### ISSUE TITLE
Unwanted space after new line

### ISSUE THREAD

**Issue by VicSegers** [gaoDean/autolist.nvim#36]
If I press `o` to create a new line, I get a new line with a space.

Output of `:nmap o`:
`*@o<Cmd>lua vim.o.operatorfunc="v:lua.require'autolist'.new"<CR><Cmd>normal! g@g@<CR><Space>`

I am using the default configuration:
`require('autolist').setup()`

Is there an easy way to get rid of the `<Space>`?

**Comment by gaoDean** [comment]
Yeah hang on, I’m just gonna make a change that makes it so the user does their own mappings. Apparently it’s way less confusing, I’ll do that later today.

**Comment by gaoDean** [comment]
okay that was not later that day, but check out the latest version
