### ISSUE TITLE
Please submit module ideas

### ISSUE THREAD

**Issue by gaoDean** [gaoDean/autolist.nvim#4]
A “module” is just the behaviour of autolist for some file. Basically how lists should be automated for some file.

Please comment a filetype (or multiple), and how the list should behave for it.

Thanks

**Comment by namjul** [comment]
Suggesting to add support for checkboxes #5

**Comment by gaoDean** [comment]
yes, perhaps if you wanted to add a module idea open an issue, and link it here like @namjul, so we can track it.

**Comment by gaoDean** [comment]
What do you guys think of LaTeX and HTML lists

**Comment by AckslD** [comment]
Have set of preceding symbols for list items configurable per filetype, such as `\item` for latex of multiple `-`s for neorg.

**Comment by davidsierradz** [comment]
Increasing list indentation when list item ending in `:`:
```
- foo:
```
Running `o` or `<CR>`:
```
- foo:
  - |
```

**Comment by gaoDean** [comment]
> Increasing list indentation when list item ending in `:`:
> 
> ```
> - foo:
> ```
> 
> Running `o` or `<CR>`:
> 
> ```
> - foo:
>   - |
> ```

Nice, will implement

**Comment by gaoDean** [comment]
just so I dont forget: tab and shift tab for empty lists

**Comment by gaoDean** [comment]
what do you guys think of deleting the whole list marker on backspace idk

**Comment by gaoDean** [comment]
> Have set of preceding symbols for list items configurable per filetype, such as `\item` for latex of multiple `-`s for neorg.

latex done, try it out

**Comment by gaoDean** [comment]
> Suggesting to add support for checkboxes #5

checkboxes done

**Comment by gaoDean** [comment]
@davidsierradz implemented, do you think it should do it without the list e.g
```
foo:
```
Running o or <CR>:
```
foo:
- |
 ```
edit: implemented anyway

**Comment by gaoDean** [comment]
imma close this cus you can just open an issue
