### ISSUE TITLE
[Performance] Do not use `autolist.new` when hitting <CR> on empty line

### ISSUE THREAD

**Issue by goingtosleep** [gaoDean/autolist.nvim#54]
Hello @gaoDean, me again 😄. Just notice that when I spam `<CR>` keys, the cursor is much slower than before. The cause is probably because of [these lines](https://github.com/gaoDean/autolist.nvim/blob/main/lua/autolist/auto.lua#L84-L87), so I tried a simple patch:

```lua
if motion == nil then
  next_keypress = mapping
  vim.o.operatorfunc = "v:lua.require'autolist'.new"
  edit_mode = vim.api.nvim_get_mode().mode

  if fn.getline('.'):find('^%s*$') then
    return '<CR>'
  end

  return "<esc>g@la"
end
```

Before:

https://user-images.githubusercontent.com/47395035/210508868-de03c7d1-c44e-4bc4-8286-d7ba0af4064b.mp4

After:

https://user-images.githubusercontent.com/47395035/210508876-cd489ed5-ac27-4bdf-ae4f-7e1d08a0243c.mp4

I think it's great if you can consider an enhancement for this.
The patch above has an issue when one uses `<CR>` as the confirmation key for `nvim-cmp`, it will automatically select the first completion when hitting `<CR>`. It's not a problem for me because I don't use select on enter, but I believe you will have a much better solution 😊

Have a good day. Thanks!

**Comment by gaoDean** [comment]
@goingtosleep thanks for the issue, im gonna try one thing and see if that improves performance. on my computer i can't really tell, so try [this pr](https://github.com/gaoDean/autolist.nvim/pull/55).

**Comment by goingtosleep** [comment]
Hmm, it's still quite sluggish I could say.

**Comment by gaoDean** [comment]
oh whoops i didn't actually make the change

**Comment by gaoDean** [comment]
@goingtosleep okay try it now

**Comment by goingtosleep** [comment]
Yes it's fast now @gaoDean, however, seems like I get the old issue with `autopairs` again. Is `autopairs` still good on your side 🤔?

**Comment by gaoDean** [comment]
Ah yes, that is a problem again.

**Comment by gaoDean** [comment]
oh im dumb, i didn't change the readme. Basically the capitalization must match the native vim capitalization of keymaps (`<cr>` should be `<CR>`)

**Comment by gaoDean** [comment]
@goingtosleep try it with the readme config in the main branch now

**Comment by goingtosleep** [comment]
Worked now, thanks a lot @gaoDean!

**Comment by goingtosleep** [comment]
It worked now. Thanks a lot @gaoDean 🎉

**Comment by gaoDean** [comment]
No problem!
