### ISSUE TITLE
Issue when undoing in various cases.

### ISSUE THREAD

**Issue by LiamKearn** [gaoDean/autolist.nvim#6]
Saw the post on reddit, thought I'd give it a go for my todo workflow.

Recreation: https://asciinema.org/a/50aeXm4N5rcTYaTn4irnPD5KJ

Steps:
1. New file.
2. Create a checkbox.
3. `yy2p` so we have 3 checkboxes.
4. Using autolist insert a new checkbox inbetween two others.
5. `dd` that checkbox and undo.
6. You should now encounter varying weird behaviour (In this case a left over `-`).

Thank you for the plugin :)

**Comment by LiamKearn** [comment]
Just as an aside have you had any thoughts about tree sitter here?

Edit: Yup as suspected the treesitter grammar for markdown detects sub-lists and could be great for this plugin:
<img width="1399" alt="Screenshot 2022-08-27 at 11 58 33 pm" src="https://user-images.githubusercontent.com/76269376/187033542-d311c4c7-e64a-4b24-970d-787491994e61.png">

This plugin does mention _minimal_ though so requiring treesitter might be a tad out of line, maybe a feature flag idea for the future?

**Comment by gaoDean** [comment]
> Just as an aside have you had any thoughts about tree sitter here?

personally I don’t use tree sitter and I have basically no experience with it, but I’ll go look and see what it can do. Btw, is tree sitter an extra dependency, or is it built in?

**Comment by gaoDean** [comment]
Ahh, the problem must be because of the use of format options comments. I have been meaning to switch away but now there is a valid reason. Thanks

**Comment by gaoDean** [comment]
@LiamKearn this should now be fixed with the removal of formatoptions

**Comment by LiamKearn** [comment]
> @LiamKearn this should now be fixed with the removal of formatoptions

Thank you very much!

Tree-sitter might save you some regex headaches. Regex is what i'd consider a "UI tool" it's great for developers to interface with arbitrary input (syntax agnostic). It does however fall short when you can offload that complexity onto a tool that will make perfect matches 95% of the time with **less input complexity** (Tree-sitter queries will be less complex and more **readable** then regex).

Tree-sitter itself isn't a parser in it's own right, it's more of a toolchain for generating parsers that will give you a syntax tree in an s-expression format. More specifically you'll want to look into querying the markdown grammer for tree-sitter. I haven't actually used tree-sitter myself aside from small one-off queries so take everything I say with a grain of salt and check out this beginner friendly video I linked someone else today :) 

Here is an example of someone using it to identify (query) a specific section of code to do some processing on it: https://www.youtube.com/watch?v=v3o9YaHBM4Q and the src for that: [interesting bit in lua that queries and passes the result to py](https://github.com/tjdevries/config_manager/blob/62b1de0f7c41d6b21c7783fdcabdb373857398ea/xdg_config/nvim/after/plugin/sql_rust_automagic.lua), the [py bit which just does some formatting](https://github.com/tjdevries/config_manager/blob/62b1de0f7c41d6b21c7783fdcabdb373857398ea/xdg_config/nvim/bin/sql-format-via-python.py) and finally the API docs to nvim-tree-sitter: https://neovim.io/doc/user/treesitter.html

That being said don't do all of this for my sake, It may be a little overkill and _not minimal_ for this use-case. I just thought it might be interesting to keep in mind for future projects if you haven't heard of it :)
