### ISSUE TITLE
Toggle Undo Conflict

### ISSUE THREAD

**Issue by benbrastmckie** [gaoDean/autolist.nvim#64]
If I have a list where I invert one of the checkboxes, I find that I can use `u` to undo that action, but continuing to press `u` does not move me any further back through my undo tree. I can still use my undotree to move into the past, but was wondering why this might be happening, and what can be done about it.

Thanks for a great plugin!

**Comment by benbrastmckie** [comment]
I think I sorted it out... apparently the trouble was caused by the following which was included in the plugin installation:
```
vim.api.nvim_create_autocmd("TextChanged", {
  pattern = "*",
  callback = function()
    vim.cmd.normal({autolist.force_recalculate(nil, nil), bang = false})
  end
})
```
After commenting that part out, undo seems to function as expected, though the auto-recalculate functionality is lost. This loss is not a big deal, but would be nice to save if there is a way to remove the bug.

**Comment by benbrastmckie** [comment]
I think I fixed it, but would like confirmation that this is the right thing to do. Here is what I now have in my plugins.lua file:
```
  use({
    "gaoDean/autolist.nvim",
    ft = {
      "markdown",
      "text",
      "tex",
      "plaintex",
    },
    config = function()
      local autolist = require("autolist")
      autolist.setup()
      autolist.create_mapping_hook("i", "<CR>", autolist.new)
      autolist.create_mapping_hook("i", "<Tab>", autolist.indent)
      autolist.create_mapping_hook("i", "<S-Tab>", autolist.indent, "<C-D>")
      autolist.create_mapping_hook("n", "o", autolist.new)
      autolist.create_mapping_hook("n", "O", autolist.new_before)
      autolist.create_mapping_hook("n", ">>", autolist.indent)
      autolist.create_mapping_hook("n", "<<", autolist.indent)
      autolist.create_mapping_hook("n", "<leader>r", autolist.force_recalculate)
      autolist.create_mapping_hook("n", "<leader>x", autolist.invert_entry, "")
        vim.api.nvim_create_autocmd("TextChanged", {
          pattern = "-",
          callback = function()
            vim.cmd.normal({autolist.force_recalculate(nil, nil), bang = false})
          end
        })
    end,
  })
```
The only change I made is to the pattern, changing it from `"*"` to `"-"`. Seems to work now. I would still prefer to move this configuration from my plugins.lua file to my autolist.lua config file, and struggling to get that to work. (I'm very new to Lua.) Any pointers would be much appreciated.

**Comment by gaoDean** [comment]
Perhaps just have the autolist.lua file return the table inside the use function, and then to use that you just do `require(whateverfile)`

**Comment by benbrastmckie** [comment]
I have required the file as with all my other config files. This is what I've tried, but without success:
```
local status_ok, autolist = pcall(require, "autolist")
if not status_ok then
  return
end

autolist.setup({
  ft = {
    "markdown",
    "text",
    "tex",
    "plaintex",
  },
  config = function()
    autolist.create_mapping_hook("i", "<CR>", autolist.new)
    autolist.create_mapping_hook("i", "<Tab>", autolist.indent)
    autolist.create_mapping_hook("i", "<S-Tab>", autolist.indent, "<C-D>")
    autolist.create_mapping_hook("n", "o", autolist.new)
    autolist.create_mapping_hook("n", "O", autolist.new_before)
    autolist.create_mapping_hook("n", ">>", autolist.indent)
    autolist.create_mapping_hook("n", "<<", autolist.indent)
    autolist.create_mapping_hook("n", "<leader>r", autolist.force_recalculate)
    autolist.create_mapping_hook("n", "<leader>x", autolist.invert_entry, "")
      vim.api.nvim_create_autocmd("TextChanged", {
        pattern = "-",
        callback = function()
          vim.cmd.normal({autolist.force_recalculate(nil, nil), bang = false})
        end
      })
  end,
})
```
I've tried other versions as well, for instance cut and pasting the exact config from the plugins.lua file.

**Comment by gaoDean** [comment]
that is not how you use the config. If you have a pulgin manager like lazy.nvim, you can specify the `ft` and `config` fields. plugging them straight into the setup function wont work. I suggest looking into a plugin manager like packer.nvim or lazy.nvim

**Comment by gaoDean** [comment]
move to https://github.com/gaoDean/autolist.nvim/issues/66
