### ISSUE TITLE
WhickKey Integration

### ISSUE THREAD

**Issue by benbrastmckie** [gaoDean/autolist.nvim#65]
I would like to integrate some of the functions that autolist provides into Whichkey, and so am looking for what command might initiate the `invert_entry` and `force_recalculate` functions. In case you don't use WhichKey, it looks like this for other plugins:
```
  ["y"] = { "<cmd>YankyRingHistory<cr>"       , "yank history" },
  ["s"] = { "<Plug>(nvim-surround-normal)", "surround" },
```
Any pointers would be greatly appreciated!

**Comment by benbrastmckie** [comment]
I think I fixed it, but would like confirmation that this is the right thing to do. Here is what I now have in my plugins.lua file:
```
  use({
    "gaoDean/autolist.nvim",
    ft = {
      "markdown",
      "text",
      "tex",
      "plaintex",
    },
    config = function()
      local autolist = require("autolist")
      autolist.setup()
      autolist.create_mapping_hook("i", "<CR>", autolist.new)
      autolist.create_mapping_hook("i", "<Tab>", autolist.indent)
      autolist.create_mapping_hook("i", "<S-Tab>", autolist.indent, "<C-D>")
      autolist.create_mapping_hook("n", "o", autolist.new)
      autolist.create_mapping_hook("n", "O", autolist.new_before)
      autolist.create_mapping_hook("n", ">>", autolist.indent)
      autolist.create_mapping_hook("n", "<<", autolist.indent)
      autolist.create_mapping_hook("n", "<leader>r", autolist.force_recalculate)
      autolist.create_mapping_hook("n", "<leader>x", autolist.invert_entry, "")
        vim.api.nvim_create_autocmd("TextChanged", {
          pattern = "-",
          callback = function()
            vim.cmd.normal({autolist.force_recalculate(nil, nil), bang = false})
          end
        })
    end,
  })
```
The only change I made is to the pattern, changing it from `"*"` to `"-"`. Seems to work now. I would still prefer to move this configuration from my plugins.lua file to my autolist.lua config file, and struggling to get that to work. (I'm very new to Lua.) Any pointers would be much appreciated.

**Comment by gaoDean** [comment]
Does which key allow for straight lua functions? those are described in the README.

**Comment by benbrastmckie** [comment]
Yes, WhichKey can run lua functions. I have tried the following:
```
:lua autolist.invert_entry()
```
These were described as public functions in the Readme. I first tried running `:lua autolist.invert_entry()` as a command (not in WhichKey), but no luck. Is there something that I'm missing?

**Comment by gaoDean** [comment]
In the readme, `autolist` is a variable described above as:

```lua
local autolist = require("autolist")
```

so it should be if you don't have the variable:

```lua
:lua require("autolist").invert_entry()
```

**Comment by benbrastmckie** [comment]
I have tried running the command:
```
:lua require("autolist").invert_entry()
```
But no dice. Is there anything else that I might be able to try? Thanks for your help.

**Comment by gaoDean** [comment]
That should run the command, is there any error message?

**Comment by benbrastmckie** [comment]
No error message, but the command does not seem to do anything.

**Comment by gaoDean** [comment]
Ah, that would be the dot-repeat being annoying. Let me fix the other issues, then I'll come back to this one.
