### ISSUE TITLE
Feature request: Maintain spaces between list marker and text

### ISSUE THREAD

**Issue by pitkling** [gaoDean/autolist.nvim#68]
Thanks for the great plugin! I have a (hopefully small?) feature request. I often come across files that have a certain number of spaces between the list marker and the text (e.g., some review forms in academic writing). It would be great if autolist would maintain the number of spaces between the list marker and the text. For example, pressing enter in the following
```
*   some text|
```
should result in
```
*   some text
*   |
```
instead of
```
*   some text
* |
```
(with `|` marking the cursor position).

**Comment by gaoDean** [comment]
Shouldn't be too hard, I'll just fix #33 before this because that seems more important.

**Comment by pitkling** [comment]
Just FYI: Works perfectly, thanks! :)
