### ISSUE TITLE
dedent increases next item number by 2

### ISSUE THREAD

**Issue by ned-si** [gaoDean/autolist.nvim#8]
Hey there,

Nice plugin!

## description

When "dedenting" an item which is not at the end of a list, the next item number increases by 2.

## to reproduce

```md
1. item a
2. item b <-- insert mode here, then <c-d> 
3. item c <-- this changes to 5. 
```

**Comment by gaoDean** [comment]
I'm currently refactoring the whole plugin, so I'll get back to you when that's done. Sorry

**Comment by gaoDean** [comment]
fixed in the rewrite, try it out @ned-si
