### ISSUE TITLE
Attempting to invert list type causes error

### ISSUE THREAD

**Issue by linduxed** [gaoDean/autolist.nvim#9]
When attempting to invert the list type (both in Insert and in Normal mode), I get the following error:

```
E5108: Error executing lua ...hare/nvim/plugged/autolist.nvim/lua/autolist/generic.lua:238: attempt to index local 'new_marker' (a nil value)
stack traceback:
        ...hare/nvim/plugged/autolist.nvim/lua/autolist/generic.lua:238: in function 'invert'
        [string ":lua"]:1: in main chunk
```

I checked where in the code `new_marker` is used, and it seems like it's used in the [`generic.invert` function](https://github.com/gaoDean/autolist.nvim/blob/9507e7c86d1ac2f2b47f7ff2274c661206d4a1eb/lua/autolist/generic.lua#L225-L252).

Since I've got `invert_toggles_checkbox = true` in my config, what I think happens is the following:

1. `new_marker` gets initialized:

https://github.com/gaoDean/autolist.nvim/blob/9507e7c86d1ac2f2b47f7ff2274c661206d4a1eb/lua/autolist/generic.lua#L228

2. The `invert_toggles_checkbox` branch is chosen:

https://github.com/gaoDean/autolist.nvim/blob/9507e7c86d1ac2f2b47f7ff2274c661206d4a1eb/lua/autolist/generic.lua#L231

3. `match` is called against `nil`, since it's only initialized to be `local`, and nothing more:

https://github.com/gaoDean/autolist.nvim/blob/9507e7c86d1ac2f2b47f7ff2274c661206d4a1eb/lua/autolist/generic.lua#L238

I might be mistaken about the chain of events, it's my best guess based on the error message.

**Comment by gaoDean** [comment]
yeah, theres a big refactor coming up, but for now I'll fix this quickly

**Comment by gaoDean** [comment]
alrihgt fixed, but the cursor position being slightly backward is a bit annoying. as said before, this will hopefully be fixed in new refactor

**Comment by linduxed** [comment]
Thank you for the fix!
